Update .golangci.yml
remove incompatible "unused" settings from linters-settings: struct as per the golangci-lint failure recommendation.
```
Error: Command failed: /home/runner/golangci-lint-1.60.2-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings.unused" does not validate with "/properties/linters-settings/properties/unused/additionalProperties": additionalProperties 'go' not allowed
Failed executing command with error: the configuration contains invalid elements
```